[build]
    publish = "docs"
    command = "npm start"
[build.processing]
    skip_processing = false
[build.processing.css]
    bundle = false
    minify = true
[build.processing.js]
    bundle = false
    minify = true
[build.processing.html]
    pretty_urls = false
[build.processing.images]
    compress = true
[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self'; img-src 'self' https://*.cloudfront.net https://www.google-analytics.com; script-src 'self' https://www.google-analytics.com https://www.googletagmanager.com; media-src 'self' https://www.youtube.com; frame-src https://www.youtube.com; form-action htps:"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        Feature-Policy = "vibrate 'none'; geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'self'; payment 'none'"